/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1XVavgY0nGb
 */
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Input } from "@/components/ui/input"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function Component() {
  return (
    (<section className="w-full py-12 md:py-24">
      <div className="container px-4 md:px-6 grid gap-6 md:gap-12 items-start">
        <div className="grid gap-6">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-2xl font-bold">Movies</h2>
              <p className="text-gray-500 dark:text-gray-400">
                Browse through a collection of popular movies grouped by date.
              </p>
            </div>
            <div className="flex items-center space-x-4">
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline">Filter</Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="w-48">
                  {movgies.map((movie) => (
                    <tr key={movie.id}>
                      <td>{movie.title}</td>
                      <td>{movie.year}</td>
                    </tr>
                  ))}
                  <DropdownMenuCheckboxItem checked={selectedGenre ==}>Action</DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem>Adventure</DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem>Comedy</DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem>Drama</DropdownMenuCheckboxItem>
                </DropdownMenuContent>
              </DropdownMenu>
              <div className="relative">
                <SearchIcon
                  className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-gray-400 dark:text-gray-500" />
                <Input className="pl-10" placeholder="Search movies..." type="search" />
              </div>
            </div>
          </div>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Date</TableHead>
                <TableHead>Movie</TableHead>
                <TableHead>Genre</TableHead>
                <TableHead>Release Year</TableHead>
                <TableHead>Duration</TableHead>
                <TableHead>Votes</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>2023-02-26</TableCell>
                <TableCell>
                  <div className="flex items-center gap-4">
                    <img
                      alt="Cover image"
                      className="rounded aspect-poster object-cover"
                      height={150}
                      src="/placeholder.svg"
                      width={100} />
                    <div className="grid gap-1.5">
                      <h3 className="font-semibold tracking-tight">The Shawshank Redemption</h3>
                      <small className="text-sm leading-none text-gray-500 dark:text-gray-400">Drama</small>
                      <div className="flex items-center gap-4">
                        <div className="flex items-center gap-0.5">
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                        </div>
                        <span className="text-sm font-medium">1994</span>
                        <span className="text-sm font-medium">142 min</span>
                        <span className="text-sm font-medium">100 votes</span>
                      </div>
                    </div>
                  </div>
                </TableCell>
                <TableCell>Drama</TableCell>
                <TableCell>1994</TableCell>
                <TableCell>142 min</TableCell>
                <TableCell>
                  <Button variant="outline">Vote</Button>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>2023-02-26</TableCell>
                <TableCell>
                  <div className="flex items-center gap-4">
                    <img
                      alt="Cover image"
                      className="rounded aspect-poster object-cover"
                      height={150}
                      src="/placeholder.svg"
                      width={100} />
                    <div className="grid gap-1.5">
                      <h3 className="font-semibold tracking-tight">The Godfather: Part II</h3>
                      <small className="text-sm leading-none text-gray-500 dark:text-gray-400">Crime, Drama</small>
                      <div className="flex items-center gap-4">
                        <div className="flex items-center gap-0.5">
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                        </div>
                        <span className="text-sm font-medium">1974</span>
                        <span className="text-sm font-medium">202 min</span>
                        <span className="text-sm font-medium">75 votes</span>
                      </div>
                    </div>
                  </div>
                </TableCell>
                <TableCell>Crime, Drama</TableCell>
                <TableCell>1974</TableCell>
                <TableCell>202 min</TableCell>
                <TableCell>
                  <Button variant="outline">Vote</Button>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>2023-02-26</TableCell>
                <TableCell>
                  <div className="flex items-center gap-4">
                    <img
                      alt="Cover image"
                      className="rounded aspect-poster object-cover"
                      height={150}
                      src="/placeholder.svg"
                      width={100} />
                    <div className="grid gap-1.5">
                      <h3 className="font-semibold tracking-tight">The Dark Knight</h3>
                      <small className="text-sm leading-none text-gray-500 dark:text-gray-400">
                        Action, Crime, Drama
                      </small>
                      <div className="flex items-center gap-4">
                        <div className="flex items-center gap-0.5">
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                        </div>
                        <span className="text-sm font-medium">2008</span>
                        <span className="text-sm font-medium">152 min</span>
                        <span className="text-sm font-medium">120 votes</span>
                      </div>
                    </div>
                  </div>
                </TableCell>
                <TableCell>Action, Crime, Drama</TableCell>
                <TableCell>2008</TableCell>
                <TableCell>152 min</TableCell>
                <TableCell>
                  <Button variant="outline">Vote</Button>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>2023-02-26</TableCell>
                <TableCell>
                  <div className="flex items-center gap-4">
                    <img
                      alt="Cover image"
                      className="rounded aspect-poster object-cover"
                      height={150}
                      src="/placeholder.svg"
                      width={100} />
                    <div className="grid gap-1.5">
                      <h3 className="font-semibold tracking-tight">The Lord of the Rings: The Return of the King</h3>
                      <small className="text-sm leading-none text-gray-500 dark:text-gray-400">
                        Adventure, Drama, Fantasy
                      </small>
                      <div className="flex items-center gap-4">
                        <div className="flex items-center gap-0.5">
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                          <StarIcon className="w-4 h-4 fill-current" />
                        </div>
                        <span className="text-sm font-medium">2003</span>
                        <span className="text-sm font-medium">201 min</span>
                        <span className="text-sm font-medium">90 votes</span>
                      </div>
                    </div>
                  </div>
                </TableCell>
                <TableCell>Adventure, Drama, Fantasy</TableCell>
                <TableCell>2003</TableCell>
                <TableCell>201 min</TableCell>
                <TableCell>
                  <Button variant="outline">Vote</Button>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </div>
    </section>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}
